#!/bin/bash

echo starting bioprj_PRJNA553831_Acanthephyra-purpurea
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA553831_Acanthephyra-purpurea/popgen divdiv_datafiles:bioprj_PRJNA553831_Acanthephyra-purpurea/popgen
echo starting bioprj_PRJNA371502_Acanthurus-olivaceus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA371502_Acanthurus-olivaceus/popgen divdiv_datafiles:bioprj_PRJNA371502_Acanthurus-olivaceus/popgen
echo starting bioprj_PRJNA473816_Acropora-cervicornis
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA473816_Acropora-cervicornis/popgen divdiv_datafiles:bioprj_PRJNA473816_Acropora-cervicornis/popgen
echo starting bioprj_PRJNA523382_Acropora-cervicornis
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA523382_Acropora-cervicornis/popgen divdiv_datafiles:bioprj_PRJNA523382_Acropora-cervicornis/popgen
echo starting bioprj_PRJNA434194_Acropora-millepora
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA434194_Acropora-millepora/popgen divdiv_datafiles:bioprj_PRJNA434194_Acropora-millepora/popgen
echo starting bioprj_PRJNA593014_Acropora-millepora
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA593014_Acropora-millepora/popgen divdiv_datafiles:bioprj_PRJNA593014_Acropora-millepora/popgen
echo starting bioprj_PRJNA473816_Acropora-palmata
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA473816_Acropora-palmata/popgen divdiv_datafiles:bioprj_PRJNA473816_Acropora-palmata/popgen
echo starting bioprj_PRJNA473816_Acropora-prolifera
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA473816_Acropora-prolifera/popgen divdiv_datafiles:bioprj_PRJNA473816_Acropora-prolifera/popgen
echo starting bioprj_PRJNA361144_Agaricia-fragilis
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA361144_Agaricia-fragilis/popgen divdiv_datafiles:bioprj_PRJNA361144_Agaricia-fragilis/popgen
echo starting bioprj_PRJNA385083_Agaricia-undata
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA385083_Agaricia-undata/popgen divdiv_datafiles:bioprj_PRJNA385083_Agaricia-undata/popgen
echo starting bioprj_PRJNA294760_Amphiprion-bicinctus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA294760_Amphiprion-bicinctus/popgen divdiv_datafiles:bioprj_PRJNA294760_Amphiprion-bicinctus/popgen
echo starting bioprj_PRJNA563695_Amphiprion-clarkii
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA563695_Amphiprion-clarkii/popgen divdiv_datafiles:bioprj_PRJNA563695_Amphiprion-clarkii/popgen
echo starting bioprj_PRJNA295681_Anguilla-anguilla
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA295681_Anguilla-anguilla/popgen divdiv_datafiles:bioprj_PRJNA295681_Anguilla-anguilla/popgen
echo starting bioprj_PRJNA295681_Anguilla-rostrata
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA295681_Anguilla-rostrata/popgen divdiv_datafiles:bioprj_PRJNA295681_Anguilla-rostrata/popgen
echo starting bioprj_PRJNA632874_Anthopleura-elegantissima
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA632874_Anthopleura-elegantissima/popgen divdiv_datafiles:bioprj_PRJNA632874_Anthopleura-elegantissima/popgen
echo starting bioprj_PRJNA436919_Apostichopus-californicus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA436919_Apostichopus-californicus/popgen divdiv_datafiles:bioprj_PRJNA436919_Apostichopus-californicus/popgen
echo starting bioprj_PRJNA343012_Aptenodytes-patagonicus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA343012_Aptenodytes-patagonicus/popgen divdiv_datafiles:bioprj_PRJNA343012_Aptenodytes-patagonicus/popgen
echo starting bioprj_PRJNA419445_Arctocephalus-forsteri
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA419445_Arctocephalus-forsteri/popgen divdiv_datafiles:bioprj_PRJNA419445_Arctocephalus-forsteri/popgen
echo starting bioprj_PRJNA299372_Aythya-marila
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA299372_Aythya-marila/popgen divdiv_datafiles:bioprj_PRJNA299372_Aythya-marila/popgen
echo starting bioprj_PRJNA542967_Bartholomea-annulata
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA542967_Bartholomea-annulata/popgen divdiv_datafiles:bioprj_PRJNA542967_Bartholomea-annulata/popgen
echo starting bioprj_PRJNA595396_Bathygobius-cocosensis
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA595396_Bathygobius-cocosensis/popgen divdiv_datafiles:bioprj_PRJNA595396_Bathygobius-cocosensis/popgen
echo starting bioprj_PRJNA473646_Bathymodiolus-platifrons
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA473646_Bathymodiolus-platifrons/popgen divdiv_datafiles:bioprj_PRJNA473646_Bathymodiolus-platifrons/popgen
echo starting bioprj_PRJNA646172_Bathyraja-aleutica
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA646172_Bathyraja-aleutica/popgen divdiv_datafiles:bioprj_PRJNA646172_Bathyraja-aleutica/popgen
echo starting bioprj_PRJNA646172_Bathyraja-panthera
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA646172_Bathyraja-panthera/popgen divdiv_datafiles:bioprj_PRJNA646172_Bathyraja-panthera/popgen
echo starting bioprj_PRJNA646172_Bathyraja-parmifera
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA646172_Bathyraja-parmifera/popgen divdiv_datafiles:bioprj_PRJNA646172_Bathyraja-parmifera/popgen
echo starting bioprj_PRJNA340157_Callinectes-sapidus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA340157_Callinectes-sapidus/popgen divdiv_datafiles:bioprj_PRJNA340157_Callinectes-sapidus/popgen
echo starting bioprj_PRJNA559677_Caretta-caretta
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA559677_Caretta-caretta/popgen divdiv_datafiles:bioprj_PRJNA559677_Caretta-caretta/popgen
echo starting bioprj_PRJNA286949_Chlorostoma-funebralis
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA286949_Chlorostoma-funebralis/popgen divdiv_datafiles:bioprj_PRJNA286949_Chlorostoma-funebralis/popgen
echo starting bioprj_PRJNA430030_Coryphaenoides-rupestris
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA430030_Coryphaenoides-rupestris/popgen divdiv_datafiles:bioprj_PRJNA430030_Coryphaenoides-rupestris/popgen
echo starting bioprj_PRJNA430094_Coryphaenoides-rupestris
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA430094_Coryphaenoides-rupestris/popgen divdiv_datafiles:bioprj_PRJNA430094_Coryphaenoides-rupestris/popgen
echo starting bioprj_PRJNA573759_Cranchia-scabra
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA573759_Cranchia-scabra/popgen divdiv_datafiles:bioprj_PRJNA573759_Cranchia-scabra/popgen
echo starting bioprj_PRJNA508986_Ctenolabrus-rupestris
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA508986_Ctenolabrus-rupestris/popgen divdiv_datafiles:bioprj_PRJNA508986_Ctenolabrus-rupestris/popgen
echo starting bioprj_PRJNA473382_Dascyllus-trimaculatus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA473382_Dascyllus-trimaculatus/popgen divdiv_datafiles:bioprj_PRJNA473382_Dascyllus-trimaculatus/popgen
echo starting bioprj_PRJNA590458_Dascyllus-trimaculatus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA590458_Dascyllus-trimaculatus/popgen divdiv_datafiles:bioprj_PRJNA590458_Dascyllus-trimaculatus/popgen
echo starting bioprj_PRJNA564823_Delphinapterus-leucas
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA564823_Delphinapterus-leucas/popgen divdiv_datafiles:bioprj_PRJNA564823_Delphinapterus-leucas/popgen
echo starting bioprj_PRJNA420851_Ectopleura-larynx
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA420851_Ectopleura-larynx/popgen divdiv_datafiles:bioprj_PRJNA420851_Ectopleura-larynx/popgen
echo starting bioprj_PRJNA311981_Engraulis-encrasicolus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA311981_Engraulis-encrasicolus/popgen divdiv_datafiles:bioprj_PRJNA311981_Engraulis-encrasicolus/popgen
echo starting bioprj_PRJNA523574_Eudyptes-chrysolophus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA523574_Eudyptes-chrysolophus/popgen divdiv_datafiles:bioprj_PRJNA523574_Eudyptes-chrysolophus/popgen
echo starting bioprj_PRJNA576675_Eukrohnia-hamata
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA576675_Eukrohnia-hamata/popgen divdiv_datafiles:bioprj_PRJNA576675_Eukrohnia-hamata/popgen
echo starting bioprj_PRJNA394157_Exaiptasia-diaphana
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA394157_Exaiptasia-diaphana/popgen divdiv_datafiles:bioprj_PRJNA394157_Exaiptasia-diaphana/popgen
echo starting bioprj_PRJDB7819_Fibramia-amboinensis
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJDB7819_Fibramia-amboinensis/popgen divdiv_datafiles:bioprj_PRJDB7819_Fibramia-amboinensis/popgen
echo starting bioprj_PRJNA629489_Fucus-vesiculosus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA629489_Fucus-vesiculosus/popgen divdiv_datafiles:bioprj_PRJNA629489_Fucus-vesiculosus/popgen
echo starting bioprj_PRJNA437462_Fundulus-grandis
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA437462_Fundulus-grandis/popgen divdiv_datafiles:bioprj_PRJNA437462_Fundulus-grandis/popgen
echo starting bioprj_PRJNA428529_Fundulus-heteroclitus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA428529_Fundulus-heteroclitus/popgen divdiv_datafiles:bioprj_PRJNA428529_Fundulus-heteroclitus/popgen
echo starting bioprj_PRJNA477712_Fundulus-heteroclitus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA477712_Fundulus-heteroclitus/popgen divdiv_datafiles:bioprj_PRJNA477712_Fundulus-heteroclitus/popgen
echo starting bioprj_PRJNA558810_Gadus-macrocephalus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA558810_Gadus-macrocephalus/popgen divdiv_datafiles:bioprj_PRJNA558810_Gadus-macrocephalus/popgen
echo starting bioprj_PRJNA521889_Gadus-morhua
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA521889_Gadus-morhua/popgen divdiv_datafiles:bioprj_PRJNA521889_Gadus-morhua/popgen
echo starting bioprj_PRJNA528403_Gadus-morhua
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA528403_Gadus-morhua/popgen divdiv_datafiles:bioprj_PRJNA528403_Gadus-morhua/popgen
echo starting bioprj_PRJNA560242_Gadus-morhua
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA560242_Gadus-morhua/popgen divdiv_datafiles:bioprj_PRJNA560242_Gadus-morhua/popgen
echo starting bioprj_PRJNA576132_Galaxea-fascicularis
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA576132_Galaxea-fascicularis/popgen divdiv_datafiles:bioprj_PRJNA576132_Galaxea-fascicularis/popgen
echo starting bioprj_PRJNA576132_Galaxea-horrescens
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA576132_Galaxea-horrescens/popgen divdiv_datafiles:bioprj_PRJNA576132_Galaxea-horrescens/popgen
echo starting bioprj_PRJNA564121_Galaxias-maculatus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA564121_Galaxias-maculatus/popgen divdiv_datafiles:bioprj_PRJNA564121_Galaxias-maculatus/popgen
echo starting bioprj_PRJNA314185_Gasterosteus-aculeatus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA314185_Gasterosteus-aculeatus/popgen divdiv_datafiles:bioprj_PRJNA314185_Gasterosteus-aculeatus/popgen
echo starting bioprj_PRJNA369168_Gasterosteus-aculeatus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA369168_Gasterosteus-aculeatus/popgen divdiv_datafiles:bioprj_PRJNA369168_Gasterosteus-aculeatus/popgen
echo starting bioprj_PRJNA453151_Gasterosteus-aculeatus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA453151_Gasterosteus-aculeatus/popgen divdiv_datafiles:bioprj_PRJNA453151_Gasterosteus-aculeatus/popgen
echo starting bioprj_PRJNA471834_Gasterosteus-aculeatus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA471834_Gasterosteus-aculeatus/popgen divdiv_datafiles:bioprj_PRJNA471834_Gasterosteus-aculeatus/popgen
echo starting bioprj_PRJNA448438_Holacanthus-passer
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA448438_Holacanthus-passer/popgen divdiv_datafiles:bioprj_PRJNA448438_Holacanthus-passer/popgen
echo starting bioprj_PRJNA281764_Homarus-americanus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA281764_Homarus-americanus/popgen divdiv_datafiles:bioprj_PRJNA281764_Homarus-americanus/popgen
echo starting bioprj_PRJNA551577_Idotea-baltica
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA551577_Idotea-baltica/popgen divdiv_datafiles:bioprj_PRJNA551577_Idotea-baltica/popgen
echo starting bioprj_PRJNA643849_Isocladus-armatus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA643849_Isocladus-armatus/popgen divdiv_datafiles:bioprj_PRJNA643849_Isocladus-armatus/popgen
echo starting bioprj_PRJNA553554_Istiblennius-lineatus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA553554_Istiblennius-lineatus/popgen divdiv_datafiles:bioprj_PRJNA553554_Istiblennius-lineatus/popgen
echo starting bioprj_PRJNA280898_Lagenorhynchus-acutus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA280898_Lagenorhynchus-acutus/popgen divdiv_datafiles:bioprj_PRJNA280898_Lagenorhynchus-acutus/popgen
echo starting bioprj_PRJNA280898_Lagenorhynchus-albirostris
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA280898_Lagenorhynchus-albirostris/popgen divdiv_datafiles:bioprj_PRJNA280898_Lagenorhynchus-albirostris/popgen
echo starting bioprj_PRJNA480409_Laguncularia-racemosa
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA480409_Laguncularia-racemosa/popgen divdiv_datafiles:bioprj_PRJNA480409_Laguncularia-racemosa/popgen
echo starting bioprj_PRJNA533707_Larimichthys-polyactis
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA533707_Larimichthys-polyactis/popgen divdiv_datafiles:bioprj_PRJNA533707_Larimichthys-polyactis/popgen
echo starting bioprj_PRJNA314732_Lateolabrax-maculatus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA314732_Lateolabrax-maculatus/popgen divdiv_datafiles:bioprj_PRJNA314732_Lateolabrax-maculatus/popgen
echo starting bioprj_PRJNA356786_Lateolabrax-maculatus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA356786_Lateolabrax-maculatus/popgen divdiv_datafiles:bioprj_PRJNA356786_Lateolabrax-maculatus/popgen
echo starting bioprj_PRJNA521302_Leptopsammia-pruvoti
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA521302_Leptopsammia-pruvoti/popgen divdiv_datafiles:bioprj_PRJNA521302_Leptopsammia-pruvoti/popgen
echo starting bioprj_PRJNA329407_Lutjanus-campechanus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA329407_Lutjanus-campechanus/popgen divdiv_datafiles:bioprj_PRJNA329407_Lutjanus-campechanus/popgen
echo starting bioprj_PRJDB7819_Lutjanus-fulvus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJDB7819_Lutjanus-fulvus/popgen divdiv_datafiles:bioprj_PRJDB7819_Lutjanus-fulvus/popgen
echo starting bioprj_PRJNA631144_Mallotus-villosus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA631144_Mallotus-villosus/popgen divdiv_datafiles:bioprj_PRJNA631144_Mallotus-villosus/popgen
echo starting bioprj_PRJNA544861_Montipora-capitata
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA544861_Montipora-capitata/popgen divdiv_datafiles:bioprj_PRJNA544861_Montipora-capitata/popgen
echo starting bioprj_PRJNA564770_Mytilus-galloprovincialis
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA564770_Mytilus-galloprovincialis/popgen divdiv_datafiles:bioprj_PRJNA564770_Mytilus-galloprovincialis/popgen
echo starting bioprj_PRJNA369717_Nautilus-pompilius
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA369717_Nautilus-pompilius/popgen divdiv_datafiles:bioprj_PRJNA369717_Nautilus-pompilius/popgen
echo starting bioprj_PRJNA170681_Nematostella-vectensis
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA170681_Nematostella-vectensis/popgen divdiv_datafiles:bioprj_PRJNA170681_Nematostella-vectensis/popgen
echo starting bioprj_PRJNA430897_Nymphon-australe
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA430897_Nymphon-australe/popgen divdiv_datafiles:bioprj_PRJNA430897_Nymphon-australe/popgen
echo starting bioprj_PRJNA343301_Oculina-patagonica
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA343301_Oculina-patagonica/popgen divdiv_datafiles:bioprj_PRJNA343301_Oculina-patagonica/popgen
echo starting bioprj_PRJNA344385_Oculina-patagonica
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA344385_Oculina-patagonica/popgen divdiv_datafiles:bioprj_PRJNA344385_Oculina-patagonica/popgen
echo starting bioprj_PRJNA508589_Orbicella-faveolata
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA508589_Orbicella-faveolata/popgen divdiv_datafiles:bioprj_PRJNA508589_Orbicella-faveolata/popgen
echo starting bioprj_PRJNA371817_Ostrea-lurida
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA371817_Ostrea-lurida/popgen divdiv_datafiles:bioprj_PRJNA371817_Ostrea-lurida/popgen
echo starting bioprj_PRJNA511386_Ostrea-lurida
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA511386_Ostrea-lurida/popgen divdiv_datafiles:bioprj_PRJNA511386_Ostrea-lurida/popgen
echo starting bioprj_PRJNA373825_Paracentrotus-lividus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA373825_Paracentrotus-lividus/popgen divdiv_datafiles:bioprj_PRJNA373825_Paracentrotus-lividus/popgen
echo starting bioprj_PRJNA640135_Paracirrhites-forsteri
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA640135_Paracirrhites-forsteri/popgen divdiv_datafiles:bioprj_PRJNA640135_Paracirrhites-forsteri/popgen
echo starting bioprj_PRJNA477007_Paralichthys-dentatus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA477007_Paralichthys-dentatus/popgen divdiv_datafiles:bioprj_PRJNA477007_Paralichthys-dentatus/popgen
echo starting bioprj_PRJNA600652_Paralichthys-dentatus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA600652_Paralichthys-dentatus/popgen divdiv_datafiles:bioprj_PRJNA600652_Paralichthys-dentatus/popgen
echo starting bioprj_PRJNA554161_Penaeus-duorarum
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA554161_Penaeus-duorarum/popgen divdiv_datafiles:bioprj_PRJNA554161_Penaeus-duorarum/popgen
echo starting bioprj_PRJNA450328_Halichoerus-grypus-atlantica
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA450328_Halichoerus-grypus-atlantica/popgen divdiv_datafiles:bioprj_PRJNA450328_Halichoerus-grypus-atlantica/popgen
echo starting bioprj_PRJNA343959_Phocoena-phocoena
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA343959_Phocoena-phocoena/popgen divdiv_datafiles:bioprj_PRJNA343959_Phocoena-phocoena/popgen
echo starting bioprj_PRJNA659918_Phocoena-phocoena
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA659918_Phocoena-phocoena/popgen divdiv_datafiles:bioprj_PRJNA659918_Phocoena-phocoena/popgen
echo starting bioprj_PRJNA659918_Phocoena-sinus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA659918_Phocoena-sinus/popgen divdiv_datafiles:bioprj_PRJNA659918_Phocoena-sinus/popgen
echo starting bioprj_PRJNA445895_Pisaster-ochraceus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA445895_Pisaster-ochraceus/popgen divdiv_datafiles:bioprj_PRJNA445895_Pisaster-ochraceus/popgen
echo starting bioprj_PRJNA340326_Placopecten-magellanicus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA340326_Placopecten-magellanicus/popgen divdiv_datafiles:bioprj_PRJNA340326_Placopecten-magellanicus/popgen
echo starting bioprj_PRJNA471559_Planes-minutus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA471559_Planes-minutus/popgen divdiv_datafiles:bioprj_PRJNA471559_Planes-minutus/popgen
echo starting bioprj_PRJNA382467_Platichthys-flesus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA382467_Platichthys-flesus/popgen divdiv_datafiles:bioprj_PRJNA382467_Platichthys-flesus/popgen
echo starting bioprj_PRJNA450871_Pocillopora-damicornis
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA450871_Pocillopora-damicornis/popgen divdiv_datafiles:bioprj_PRJNA450871_Pocillopora-damicornis/popgen
echo starting bioprj_PRJNA280774_Poecilia-latipinna
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA280774_Poecilia-latipinna/popgen divdiv_datafiles:bioprj_PRJNA280774_Poecilia-latipinna/popgen
echo starting bioprj_PRJNA559876_Pomacanthus-maculosus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA559876_Pomacanthus-maculosus/popgen divdiv_datafiles:bioprj_PRJNA559876_Pomacanthus-maculosus/popgen
echo starting bioprj_PRJNA379028_Porites-astreoides
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA379028_Porites-astreoides/popgen divdiv_datafiles:bioprj_PRJNA379028_Porites-astreoides/popgen
echo starting bioprj_PRJNA544861_Porites-compressa
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA544861_Porites-compressa/popgen divdiv_datafiles:bioprj_PRJNA544861_Porites-compressa/popgen
echo starting bioprj_PRJNA210803_Pygoscelis-adeliae
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA210803_Pygoscelis-adeliae/popgen divdiv_datafiles:bioprj_PRJNA210803_Pygoscelis-adeliae/popgen
echo starting bioprj_PRJNA493660_Pygoscelis-adeliae
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA493660_Pygoscelis-adeliae/popgen divdiv_datafiles:bioprj_PRJNA493660_Pygoscelis-adeliae/popgen
echo starting bioprj_PRJNA544154_Pygoscelis-adeliae
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA544154_Pygoscelis-adeliae/popgen divdiv_datafiles:bioprj_PRJNA544154_Pygoscelis-adeliae/popgen
echo starting bioprj_PRJNA493660_Pygoscelis-antarcticus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA493660_Pygoscelis-antarcticus/popgen divdiv_datafiles:bioprj_PRJNA493660_Pygoscelis-antarcticus/popgen
echo starting bioprj_PRJNA493660_Pygoscelis-papua
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA493660_Pygoscelis-papua/popgen divdiv_datafiles:bioprj_PRJNA493660_Pygoscelis-papua/popgen
echo starting bioprj_PRJNA573759_Pyroteuthis-margaritifera
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA573759_Pyroteuthis-margaritifera/popgen divdiv_datafiles:bioprj_PRJNA573759_Pyroteuthis-margaritifera/popgen
echo starting bioprj_PRJNA397667_Rhizophora-mangle
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA397667_Rhizophora-mangle/popgen divdiv_datafiles:bioprj_PRJNA397667_Rhizophora-mangle/popgen
echo starting bioprj_PRJNA480308_Rhizophora-mangle
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA480308_Rhizophora-mangle/popgen divdiv_datafiles:bioprj_PRJNA480308_Rhizophora-mangle/popgen
echo starting bioprj_PRJNA553831_Robustosergia-robusta
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA553831_Robustosergia-robusta/popgen divdiv_datafiles:bioprj_PRJNA553831_Robustosergia-robusta/popgen
echo starting bioprj_PRJNA549138_Sargassum-muticum
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA549138_Sargassum-muticum/popgen divdiv_datafiles:bioprj_PRJNA549138_Sargassum-muticum/popgen
echo starting bioprj_PRJNA253681_Scomber-scombrus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA253681_Scomber-scombrus/popgen divdiv_datafiles:bioprj_PRJNA253681_Scomber-scombrus/popgen
echo starting bioprj_PRJNA560239_Sebastes-diaconus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA560239_Sebastes-diaconus/popgen divdiv_datafiles:bioprj_PRJNA560239_Sebastes-diaconus/popgen
echo starting bioprj_PRJNA451040_Sebastes-paucispinis
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA451040_Sebastes-paucispinis/popgen divdiv_datafiles:bioprj_PRJNA451040_Sebastes-paucispinis/popgen
echo starting bioprj_PRJNA451040_Sebastes-pinniger
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA451040_Sebastes-pinniger/popgen divdiv_datafiles:bioprj_PRJNA451040_Sebastes-pinniger/popgen
echo starting bioprj_PRJNA316872_Sebastes-rastrelliger
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA316872_Sebastes-rastrelliger/popgen divdiv_datafiles:bioprj_PRJNA316872_Sebastes-rastrelliger/popgen
echo starting bioprj_PRJNA451040_Sebastes-ruberrimus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA451040_Sebastes-ruberrimus/popgen divdiv_datafiles:bioprj_PRJNA451040_Sebastes-ruberrimus/popgen
echo starting bioprj_PRJNA359404_Sebastiscus-marmoratus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA359404_Sebastiscus-marmoratus/popgen divdiv_datafiles:bioprj_PRJNA359404_Sebastiscus-marmoratus/popgen
echo starting bioprj_PRJNA392526_Sebastiscus-marmoratus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA392526_Sebastiscus-marmoratus/popgen divdiv_datafiles:bioprj_PRJNA392526_Sebastiscus-marmoratus/popgen
echo starting bioprj_PRJNA319656_Seriola-lalandi-dorsalis
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA319656_Seriola-lalandi-dorsalis/popgen divdiv_datafiles:bioprj_PRJNA319656_Seriola-lalandi-dorsalis/popgen
echo starting bioprj_PRJNA385011_Siphamia-tubifer
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA385011_Siphamia-tubifer/popgen divdiv_datafiles:bioprj_PRJNA385011_Siphamia-tubifer/popgen
echo starting bioprj_PRJNA286089_Sphyrna-tiburo
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA286089_Sphyrna-tiburo/popgen divdiv_datafiles:bioprj_PRJNA286089_Sphyrna-tiburo/popgen
echo starting bioprj_PRJNA448430_Stegastes-beebei
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA448430_Stegastes-beebei/popgen divdiv_datafiles:bioprj_PRJNA448430_Stegastes-beebei/popgen
echo starting bioprj_PRJNA448430_Stegastes-leucorus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA448430_Stegastes-leucorus/popgen divdiv_datafiles:bioprj_PRJNA448430_Stegastes-leucorus/popgen
echo starting bioprj_PRJNA361144_Stephanocoenia-intersepta
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA361144_Stephanocoenia-intersepta/popgen divdiv_datafiles:bioprj_PRJNA361144_Stephanocoenia-intersepta/popgen
echo starting bioprj_PRJNA655996_Strombus-pugilis
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA655996_Strombus-pugilis/popgen divdiv_datafiles:bioprj_PRJNA655996_Strombus-pugilis/popgen
echo starting bioprj_PRJNA354496_Symphodus-melops
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA354496_Symphodus-melops/popgen divdiv_datafiles:bioprj_PRJNA354496_Symphodus-melops/popgen
echo starting bioprj_PRJNA361214_Symphodus-tinca
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA361214_Symphodus-tinca/popgen divdiv_datafiles:bioprj_PRJNA361214_Symphodus-tinca/popgen
echo starting bioprj_PRJNA553831_Systellaspis-debilis
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA553831_Systellaspis-debilis/popgen divdiv_datafiles:bioprj_PRJNA553831_Systellaspis-debilis/popgen
echo starting bioprj_PRJNA432036_Thunnus-thynnus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA432036_Thunnus-thynnus/popgen divdiv_datafiles:bioprj_PRJNA432036_Thunnus-thynnus/popgen
echo starting bioprj_PRJNA360511_Trachidermus-fasciatus
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA360511_Trachidermus-fasciatus/popgen divdiv_datafiles:bioprj_PRJNA360511_Trachidermus-fasciatus/popgen
echo starting bioprj_PRJNA564451_Uria-aalge
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA564451_Uria-aalge/popgen divdiv_datafiles:bioprj_PRJNA564451_Uria-aalge/popgen
echo starting bioprj_PRJNA564451_Uria-lomvia
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA564451_Uria-lomvia/popgen divdiv_datafiles:bioprj_PRJNA564451_Uria-lomvia/popgen
echo starting bioprj_PRJNA573759_Vampyroteuthis-infernalis
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA573759_Vampyroteuthis-infernalis/popgen divdiv_datafiles:bioprj_PRJNA573759_Vampyroteuthis-infernalis/popgen
echo starting bioprj_PRJNA348572_Zalophus-wollebaeki
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA348572_Zalophus-wollebaeki/popgen divdiv_datafiles:bioprj_PRJNA348572_Zalophus-wollebaeki/popgen
echo starting bioprj_PRJNA449377_Zebrasoma-flavescens
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA449377_Zebrasoma-flavescens/popgen divdiv_datafiles:bioprj_PRJNA449377_Zebrasoma-flavescens/popgen
echo starting bioprj_PRJNA449377_Zebrasoma-scopas
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJNA449377_Zebrasoma-scopas/popgen divdiv_datafiles:bioprj_PRJNA449377_Zebrasoma-scopas/popgen
echo starting bioprj_PRJDB7819_Zenarchopterus-dunckeri
rclone copy /mnt/scratch/rhtoczyd/bioprj_PRJDB7819_Zenarchopterus-dunckeri/popgen divdiv_datafiles:bioprj_PRJDB7819_Zenarchopterus-dunckeri/popgen


