#!/bin/bash

echo starting bioprj_PRJNA553831_Acanthephyra-purpurea
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA553831_Acanthephyra-purpurea/genetic_data divdiv_datafiles:bioprj_PRJNA553831_Acanthephyra-purpurea/genetic_data
echo starting bioprj_PRJNA371502_Acanthurus-olivaceus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA371502_Acanthurus-olivaceus/genetic_data divdiv_datafiles:bioprj_PRJNA371502_Acanthurus-olivaceus/genetic_data
echo starting bioprj_PRJNA473816_Acropora-cervicornis
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA473816_Acropora-cervicornis/genetic_data divdiv_datafiles:bioprj_PRJNA473816_Acropora-cervicornis/genetic_data
echo starting bioprj_PRJNA523382_Acropora-cervicornis
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA523382_Acropora-cervicornis/genetic_data divdiv_datafiles:bioprj_PRJNA523382_Acropora-cervicornis/genetic_data
echo starting bioprj_PRJNA434194_Acropora-millepora
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA434194_Acropora-millepora/genetic_data divdiv_datafiles:bioprj_PRJNA434194_Acropora-millepora/genetic_data
echo starting bioprj_PRJNA593014_Acropora-millepora
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA593014_Acropora-millepora/genetic_data divdiv_datafiles:bioprj_PRJNA593014_Acropora-millepora/genetic_data
echo starting bioprj_PRJNA473816_Acropora-palmata
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA473816_Acropora-palmata/genetic_data divdiv_datafiles:bioprj_PRJNA473816_Acropora-palmata/genetic_data
echo starting bioprj_PRJNA473816_Acropora-prolifera
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA473816_Acropora-prolifera/genetic_data divdiv_datafiles:bioprj_PRJNA473816_Acropora-prolifera/genetic_data
echo starting bioprj_PRJNA361144_Agaricia-fragilis
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA361144_Agaricia-fragilis/genetic_data divdiv_datafiles:bioprj_PRJNA361144_Agaricia-fragilis/genetic_data
echo starting bioprj_PRJNA385083_Agaricia-undata
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA385083_Agaricia-undata/genetic_data divdiv_datafiles:bioprj_PRJNA385083_Agaricia-undata/genetic_data
echo starting bioprj_PRJNA294760_Amphiprion-bicinctus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA294760_Amphiprion-bicinctus/genetic_data divdiv_datafiles:bioprj_PRJNA294760_Amphiprion-bicinctus/genetic_data
echo starting bioprj_PRJNA563695_Amphiprion-clarkii
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA563695_Amphiprion-clarkii/genetic_data divdiv_datafiles:bioprj_PRJNA563695_Amphiprion-clarkii/genetic_data
echo starting bioprj_PRJNA295681_Anguilla-anguilla
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA295681_Anguilla-anguilla/genetic_data divdiv_datafiles:bioprj_PRJNA295681_Anguilla-anguilla/genetic_data
echo starting bioprj_PRJNA295681_Anguilla-rostrata
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA295681_Anguilla-rostrata/genetic_data divdiv_datafiles:bioprj_PRJNA295681_Anguilla-rostrata/genetic_data
echo starting bioprj_PRJNA632874_Anthopleura-elegantissima
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA632874_Anthopleura-elegantissima/genetic_data divdiv_datafiles:bioprj_PRJNA632874_Anthopleura-elegantissima/genetic_data
echo starting bioprj_PRJNA436919_Apostichopus-californicus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA436919_Apostichopus-californicus/genetic_data divdiv_datafiles:bioprj_PRJNA436919_Apostichopus-californicus/genetic_data
echo starting bioprj_PRJNA343012_Aptenodytes-patagonicus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA343012_Aptenodytes-patagonicus/genetic_data divdiv_datafiles:bioprj_PRJNA343012_Aptenodytes-patagonicus/genetic_data
echo starting bioprj_PRJNA419445_Arctocephalus-forsteri
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA419445_Arctocephalus-forsteri/genetic_data divdiv_datafiles:bioprj_PRJNA419445_Arctocephalus-forsteri/genetic_data
echo starting bioprj_PRJNA299372_Aythya-marila
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA299372_Aythya-marila/genetic_data divdiv_datafiles:bioprj_PRJNA299372_Aythya-marila/genetic_data
echo starting bioprj_PRJNA542967_Bartholomea-annulata
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA542967_Bartholomea-annulata/genetic_data divdiv_datafiles:bioprj_PRJNA542967_Bartholomea-annulata/genetic_data
echo starting bioprj_PRJNA595396_Bathygobius-cocosensis
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA595396_Bathygobius-cocosensis/genetic_data divdiv_datafiles:bioprj_PRJNA595396_Bathygobius-cocosensis/genetic_data
echo starting bioprj_PRJNA473646_Bathymodiolus-platifrons
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA473646_Bathymodiolus-platifrons/genetic_data divdiv_datafiles:bioprj_PRJNA473646_Bathymodiolus-platifrons/genetic_data
echo starting bioprj_PRJNA646172_Bathyraja-aleutica
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA646172_Bathyraja-aleutica/genetic_data divdiv_datafiles:bioprj_PRJNA646172_Bathyraja-aleutica/genetic_data
echo starting bioprj_PRJNA646172_Bathyraja-panthera
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA646172_Bathyraja-panthera/genetic_data divdiv_datafiles:bioprj_PRJNA646172_Bathyraja-panthera/genetic_data
echo starting bioprj_PRJNA646172_Bathyraja-parmifera
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA646172_Bathyraja-parmifera/genetic_data divdiv_datafiles:bioprj_PRJNA646172_Bathyraja-parmifera/genetic_data
echo starting bioprj_PRJNA340157_Callinectes-sapidus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA340157_Callinectes-sapidus/genetic_data divdiv_datafiles:bioprj_PRJNA340157_Callinectes-sapidus/genetic_data
echo starting bioprj_PRJNA559677_Caretta-caretta
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA559677_Caretta-caretta/genetic_data divdiv_datafiles:bioprj_PRJNA559677_Caretta-caretta/genetic_data
echo starting bioprj_PRJNA286949_Chlorostoma-funebralis
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA286949_Chlorostoma-funebralis/genetic_data divdiv_datafiles:bioprj_PRJNA286949_Chlorostoma-funebralis/genetic_data
echo starting bioprj_PRJNA430030_Coryphaenoides-rupestris
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA430030_Coryphaenoides-rupestris/genetic_data divdiv_datafiles:bioprj_PRJNA430030_Coryphaenoides-rupestris/genetic_data
echo starting bioprj_PRJNA430094_Coryphaenoides-rupestris
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA430094_Coryphaenoides-rupestris/genetic_data divdiv_datafiles:bioprj_PRJNA430094_Coryphaenoides-rupestris/genetic_data
echo starting bioprj_PRJNA573759_Cranchia-scabra
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA573759_Cranchia-scabra/genetic_data divdiv_datafiles:bioprj_PRJNA573759_Cranchia-scabra/genetic_data
echo starting bioprj_PRJNA508986_Ctenolabrus-rupestris
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA508986_Ctenolabrus-rupestris/genetic_data divdiv_datafiles:bioprj_PRJNA508986_Ctenolabrus-rupestris/genetic_data
echo starting bioprj_PRJNA473382_Dascyllus-trimaculatus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA473382_Dascyllus-trimaculatus/genetic_data divdiv_datafiles:bioprj_PRJNA473382_Dascyllus-trimaculatus/genetic_data
echo starting bioprj_PRJNA590458_Dascyllus-trimaculatus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA590458_Dascyllus-trimaculatus/genetic_data divdiv_datafiles:bioprj_PRJNA590458_Dascyllus-trimaculatus/genetic_data
echo starting bioprj_PRJNA564823_Delphinapterus-leucas
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA564823_Delphinapterus-leucas/genetic_data divdiv_datafiles:bioprj_PRJNA564823_Delphinapterus-leucas/genetic_data
echo starting bioprj_PRJNA420851_Ectopleura-larynx
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA420851_Ectopleura-larynx/genetic_data divdiv_datafiles:bioprj_PRJNA420851_Ectopleura-larynx/genetic_data
echo starting bioprj_PRJNA311981_Engraulis-encrasicolus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA311981_Engraulis-encrasicolus/genetic_data divdiv_datafiles:bioprj_PRJNA311981_Engraulis-encrasicolus/genetic_data
echo starting bioprj_PRJNA523574_Eudyptes-chrysolophus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA523574_Eudyptes-chrysolophus/genetic_data divdiv_datafiles:bioprj_PRJNA523574_Eudyptes-chrysolophus/genetic_data
echo starting bioprj_PRJNA576675_Eukrohnia-hamata
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA576675_Eukrohnia-hamata/genetic_data divdiv_datafiles:bioprj_PRJNA576675_Eukrohnia-hamata/genetic_data
echo starting bioprj_PRJNA394157_Exaiptasia-diaphana
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA394157_Exaiptasia-diaphana/genetic_data divdiv_datafiles:bioprj_PRJNA394157_Exaiptasia-diaphana/genetic_data
echo starting bioprj_PRJDB7819_Fibramia-amboinensis
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJDB7819_Fibramia-amboinensis/genetic_data divdiv_datafiles:bioprj_PRJDB7819_Fibramia-amboinensis/genetic_data
echo starting bioprj_PRJNA629489_Fucus-vesiculosus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA629489_Fucus-vesiculosus/genetic_data divdiv_datafiles:bioprj_PRJNA629489_Fucus-vesiculosus/genetic_data
echo starting bioprj_PRJNA437462_Fundulus-grandis
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA437462_Fundulus-grandis/genetic_data divdiv_datafiles:bioprj_PRJNA437462_Fundulus-grandis/genetic_data
echo starting bioprj_PRJNA428529_Fundulus-heteroclitus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA428529_Fundulus-heteroclitus/genetic_data divdiv_datafiles:bioprj_PRJNA428529_Fundulus-heteroclitus/genetic_data
echo starting bioprj_PRJNA477712_Fundulus-heteroclitus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA477712_Fundulus-heteroclitus/genetic_data divdiv_datafiles:bioprj_PRJNA477712_Fundulus-heteroclitus/genetic_data
echo starting bioprj_PRJNA558810_Gadus-macrocephalus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA558810_Gadus-macrocephalus/genetic_data divdiv_datafiles:bioprj_PRJNA558810_Gadus-macrocephalus/genetic_data
echo starting bioprj_PRJNA521889_Gadus-morhua
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA521889_Gadus-morhua/genetic_data divdiv_datafiles:bioprj_PRJNA521889_Gadus-morhua/genetic_data
echo starting bioprj_PRJNA528403_Gadus-morhua
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA528403_Gadus-morhua/genetic_data divdiv_datafiles:bioprj_PRJNA528403_Gadus-morhua/genetic_data
echo starting bioprj_PRJNA560242_Gadus-morhua
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA560242_Gadus-morhua/genetic_data divdiv_datafiles:bioprj_PRJNA560242_Gadus-morhua/genetic_data
echo starting bioprj_PRJNA576132_Galaxea-fascicularis
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA576132_Galaxea-fascicularis/genetic_data divdiv_datafiles:bioprj_PRJNA576132_Galaxea-fascicularis/genetic_data
echo starting bioprj_PRJNA576132_Galaxea-horrescens
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA576132_Galaxea-horrescens/genetic_data divdiv_datafiles:bioprj_PRJNA576132_Galaxea-horrescens/genetic_data
echo starting bioprj_PRJNA564121_Galaxias-maculatus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA564121_Galaxias-maculatus/genetic_data divdiv_datafiles:bioprj_PRJNA564121_Galaxias-maculatus/genetic_data
echo starting bioprj_PRJNA314185_Gasterosteus-aculeatus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA314185_Gasterosteus-aculeatus/genetic_data divdiv_datafiles:bioprj_PRJNA314185_Gasterosteus-aculeatus/genetic_data
echo starting bioprj_PRJNA369168_Gasterosteus-aculeatus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA369168_Gasterosteus-aculeatus/genetic_data divdiv_datafiles:bioprj_PRJNA369168_Gasterosteus-aculeatus/genetic_data
echo starting bioprj_PRJNA453151_Gasterosteus-aculeatus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA453151_Gasterosteus-aculeatus/genetic_data divdiv_datafiles:bioprj_PRJNA453151_Gasterosteus-aculeatus/genetic_data
echo starting bioprj_PRJNA471834_Gasterosteus-aculeatus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA471834_Gasterosteus-aculeatus/genetic_data divdiv_datafiles:bioprj_PRJNA471834_Gasterosteus-aculeatus/genetic_data
echo starting bioprj_PRJNA448438_Holacanthus-passer
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA448438_Holacanthus-passer/genetic_data divdiv_datafiles:bioprj_PRJNA448438_Holacanthus-passer/genetic_data
echo starting bioprj_PRJNA281764_Homarus-americanus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA281764_Homarus-americanus/genetic_data divdiv_datafiles:bioprj_PRJNA281764_Homarus-americanus/genetic_data
echo starting bioprj_PRJNA551577_Idotea-baltica
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA551577_Idotea-baltica/genetic_data divdiv_datafiles:bioprj_PRJNA551577_Idotea-baltica/genetic_data
echo starting bioprj_PRJNA643849_Isocladus-armatus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA643849_Isocladus-armatus/genetic_data divdiv_datafiles:bioprj_PRJNA643849_Isocladus-armatus/genetic_data
echo starting bioprj_PRJNA553554_Istiblennius-lineatus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA553554_Istiblennius-lineatus/genetic_data divdiv_datafiles:bioprj_PRJNA553554_Istiblennius-lineatus/genetic_data
echo starting bioprj_PRJNA280898_Lagenorhynchus-acutus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA280898_Lagenorhynchus-acutus/genetic_data divdiv_datafiles:bioprj_PRJNA280898_Lagenorhynchus-acutus/genetic_data
echo starting bioprj_PRJNA280898_Lagenorhynchus-albirostris
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA280898_Lagenorhynchus-albirostris/genetic_data divdiv_datafiles:bioprj_PRJNA280898_Lagenorhynchus-albirostris/genetic_data
echo starting bioprj_PRJNA480409_Laguncularia-racemosa
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA480409_Laguncularia-racemosa/genetic_data divdiv_datafiles:bioprj_PRJNA480409_Laguncularia-racemosa/genetic_data
echo starting bioprj_PRJNA533707_Larimichthys-polyactis
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA533707_Larimichthys-polyactis/genetic_data divdiv_datafiles:bioprj_PRJNA533707_Larimichthys-polyactis/genetic_data
echo starting bioprj_PRJNA314732_Lateolabrax-maculatus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA314732_Lateolabrax-maculatus/genetic_data divdiv_datafiles:bioprj_PRJNA314732_Lateolabrax-maculatus/genetic_data
echo starting bioprj_PRJNA356786_Lateolabrax-maculatus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA356786_Lateolabrax-maculatus/genetic_data divdiv_datafiles:bioprj_PRJNA356786_Lateolabrax-maculatus/genetic_data
echo starting bioprj_PRJNA521302_Leptopsammia-pruvoti
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA521302_Leptopsammia-pruvoti/genetic_data divdiv_datafiles:bioprj_PRJNA521302_Leptopsammia-pruvoti/genetic_data
echo starting bioprj_PRJNA329407_Lutjanus-campechanus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA329407_Lutjanus-campechanus/genetic_data divdiv_datafiles:bioprj_PRJNA329407_Lutjanus-campechanus/genetic_data
echo starting bioprj_PRJDB7819_Lutjanus-fulvus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJDB7819_Lutjanus-fulvus/genetic_data divdiv_datafiles:bioprj_PRJDB7819_Lutjanus-fulvus/genetic_data
echo starting bioprj_PRJNA631144_Mallotus-villosus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA631144_Mallotus-villosus/genetic_data divdiv_datafiles:bioprj_PRJNA631144_Mallotus-villosus/genetic_data
echo starting bioprj_PRJNA544861_Montipora-capitata
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA544861_Montipora-capitata/genetic_data divdiv_datafiles:bioprj_PRJNA544861_Montipora-capitata/genetic_data
echo starting bioprj_PRJNA564770_Mytilus-galloprovincialis
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA564770_Mytilus-galloprovincialis/genetic_data divdiv_datafiles:bioprj_PRJNA564770_Mytilus-galloprovincialis/genetic_data
echo starting bioprj_PRJNA369717_Nautilus-pompilius
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA369717_Nautilus-pompilius/genetic_data divdiv_datafiles:bioprj_PRJNA369717_Nautilus-pompilius/genetic_data
echo starting bioprj_PRJNA170681_Nematostella-vectensis
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA170681_Nematostella-vectensis/genetic_data divdiv_datafiles:bioprj_PRJNA170681_Nematostella-vectensis/genetic_data
echo starting bioprj_PRJNA430897_Nymphon-australe
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA430897_Nymphon-australe/genetic_data divdiv_datafiles:bioprj_PRJNA430897_Nymphon-australe/genetic_data
echo starting bioprj_PRJNA343301_Oculina-patagonica
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA343301_Oculina-patagonica/genetic_data divdiv_datafiles:bioprj_PRJNA343301_Oculina-patagonica/genetic_data
echo starting bioprj_PRJNA344385_Oculina-patagonica
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA344385_Oculina-patagonica/genetic_data divdiv_datafiles:bioprj_PRJNA344385_Oculina-patagonica/genetic_data
echo starting bioprj_PRJNA508589_Orbicella-faveolata
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA508589_Orbicella-faveolata/genetic_data divdiv_datafiles:bioprj_PRJNA508589_Orbicella-faveolata/genetic_data
echo starting bioprj_PRJNA371817_Ostrea-lurida
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA371817_Ostrea-lurida/genetic_data divdiv_datafiles:bioprj_PRJNA371817_Ostrea-lurida/genetic_data
echo starting bioprj_PRJNA511386_Ostrea-lurida
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA511386_Ostrea-lurida/genetic_data divdiv_datafiles:bioprj_PRJNA511386_Ostrea-lurida/genetic_data
echo starting bioprj_PRJNA373825_Paracentrotus-lividus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA373825_Paracentrotus-lividus/genetic_data divdiv_datafiles:bioprj_PRJNA373825_Paracentrotus-lividus/genetic_data
echo starting bioprj_PRJNA640135_Paracirrhites-forsteri
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA640135_Paracirrhites-forsteri/genetic_data divdiv_datafiles:bioprj_PRJNA640135_Paracirrhites-forsteri/genetic_data
echo starting bioprj_PRJNA477007_Paralichthys-dentatus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA477007_Paralichthys-dentatus/genetic_data divdiv_datafiles:bioprj_PRJNA477007_Paralichthys-dentatus/genetic_data
echo starting bioprj_PRJNA600652_Paralichthys-dentatus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA600652_Paralichthys-dentatus/genetic_data divdiv_datafiles:bioprj_PRJNA600652_Paralichthys-dentatus/genetic_data
echo starting bioprj_PRJNA554161_Penaeus-duorarum
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA554161_Penaeus-duorarum/genetic_data divdiv_datafiles:bioprj_PRJNA554161_Penaeus-duorarum/genetic_data
echo starting bioprj_PRJNA450328_Halichoerus-grypus-atlantica
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA450328_Halichoerus-grypus-atlantica/genetic_data divdiv_datafiles:bioprj_PRJNA450328_Halichoerus-grypus-atlantica/genetic_data
echo starting bioprj_PRJNA343959_Phocoena-phocoena
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA343959_Phocoena-phocoena/genetic_data divdiv_datafiles:bioprj_PRJNA343959_Phocoena-phocoena/genetic_data
echo starting bioprj_PRJNA659918_Phocoena-phocoena
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA659918_Phocoena-phocoena/genetic_data divdiv_datafiles:bioprj_PRJNA659918_Phocoena-phocoena/genetic_data
echo starting bioprj_PRJNA659918_Phocoena-sinus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA659918_Phocoena-sinus/genetic_data divdiv_datafiles:bioprj_PRJNA659918_Phocoena-sinus/genetic_data
echo starting bioprj_PRJNA445895_Pisaster-ochraceus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA445895_Pisaster-ochraceus/genetic_data divdiv_datafiles:bioprj_PRJNA445895_Pisaster-ochraceus/genetic_data
echo starting bioprj_PRJNA340326_Placopecten-magellanicus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA340326_Placopecten-magellanicus/genetic_data divdiv_datafiles:bioprj_PRJNA340326_Placopecten-magellanicus/genetic_data
echo starting bioprj_PRJNA471559_Planes-minutus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA471559_Planes-minutus/genetic_data divdiv_datafiles:bioprj_PRJNA471559_Planes-minutus/genetic_data
echo starting bioprj_PRJNA382467_Platichthys-flesus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA382467_Platichthys-flesus/genetic_data divdiv_datafiles:bioprj_PRJNA382467_Platichthys-flesus/genetic_data
echo starting bioprj_PRJNA450871_Pocillopora-damicornis
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA450871_Pocillopora-damicornis/genetic_data divdiv_datafiles:bioprj_PRJNA450871_Pocillopora-damicornis/genetic_data
echo starting bioprj_PRJNA280774_Poecilia-latipinna
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA280774_Poecilia-latipinna/genetic_data divdiv_datafiles:bioprj_PRJNA280774_Poecilia-latipinna/genetic_data
echo starting bioprj_PRJNA559876_Pomacanthus-maculosus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA559876_Pomacanthus-maculosus/genetic_data divdiv_datafiles:bioprj_PRJNA559876_Pomacanthus-maculosus/genetic_data
echo starting bioprj_PRJNA379028_Porites-astreoides
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA379028_Porites-astreoides/genetic_data divdiv_datafiles:bioprj_PRJNA379028_Porites-astreoides/genetic_data
echo starting bioprj_PRJNA544861_Porites-compressa
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA544861_Porites-compressa/genetic_data divdiv_datafiles:bioprj_PRJNA544861_Porites-compressa/genetic_data
echo starting bioprj_PRJNA210803_Pygoscelis-adeliae
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA210803_Pygoscelis-adeliae/genetic_data divdiv_datafiles:bioprj_PRJNA210803_Pygoscelis-adeliae/genetic_data
echo starting bioprj_PRJNA493660_Pygoscelis-adeliae
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA493660_Pygoscelis-adeliae/genetic_data divdiv_datafiles:bioprj_PRJNA493660_Pygoscelis-adeliae/genetic_data
echo starting bioprj_PRJNA544154_Pygoscelis-adeliae
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA544154_Pygoscelis-adeliae/genetic_data divdiv_datafiles:bioprj_PRJNA544154_Pygoscelis-adeliae/genetic_data
echo starting bioprj_PRJNA493660_Pygoscelis-antarcticus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA493660_Pygoscelis-antarcticus/genetic_data divdiv_datafiles:bioprj_PRJNA493660_Pygoscelis-antarcticus/genetic_data
echo starting bioprj_PRJNA493660_Pygoscelis-papua
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA493660_Pygoscelis-papua/genetic_data divdiv_datafiles:bioprj_PRJNA493660_Pygoscelis-papua/genetic_data
echo starting bioprj_PRJNA573759_Pyroteuthis-margaritifera
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA573759_Pyroteuthis-margaritifera/genetic_data divdiv_datafiles:bioprj_PRJNA573759_Pyroteuthis-margaritifera/genetic_data
echo starting bioprj_PRJNA397667_Rhizophora-mangle
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA397667_Rhizophora-mangle/genetic_data divdiv_datafiles:bioprj_PRJNA397667_Rhizophora-mangle/genetic_data
echo starting bioprj_PRJNA480308_Rhizophora-mangle
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA480308_Rhizophora-mangle/genetic_data divdiv_datafiles:bioprj_PRJNA480308_Rhizophora-mangle/genetic_data
echo starting bioprj_PRJNA553831_Robustosergia-robusta
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA553831_Robustosergia-robusta/genetic_data divdiv_datafiles:bioprj_PRJNA553831_Robustosergia-robusta/genetic_data
echo starting bioprj_PRJNA549138_Sargassum-muticum
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA549138_Sargassum-muticum/genetic_data divdiv_datafiles:bioprj_PRJNA549138_Sargassum-muticum/genetic_data
echo starting bioprj_PRJNA253681_Scomber-scombrus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA253681_Scomber-scombrus/genetic_data divdiv_datafiles:bioprj_PRJNA253681_Scomber-scombrus/genetic_data
echo starting bioprj_PRJNA560239_Sebastes-diaconus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA560239_Sebastes-diaconus/genetic_data divdiv_datafiles:bioprj_PRJNA560239_Sebastes-diaconus/genetic_data
echo starting bioprj_PRJNA451040_Sebastes-paucispinis
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA451040_Sebastes-paucispinis/genetic_data divdiv_datafiles:bioprj_PRJNA451040_Sebastes-paucispinis/genetic_data
echo starting bioprj_PRJNA451040_Sebastes-pinniger
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA451040_Sebastes-pinniger/genetic_data divdiv_datafiles:bioprj_PRJNA451040_Sebastes-pinniger/genetic_data
echo starting bioprj_PRJNA316872_Sebastes-rastrelliger
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA316872_Sebastes-rastrelliger/genetic_data divdiv_datafiles:bioprj_PRJNA316872_Sebastes-rastrelliger/genetic_data
echo starting bioprj_PRJNA451040_Sebastes-ruberrimus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA451040_Sebastes-ruberrimus/genetic_data divdiv_datafiles:bioprj_PRJNA451040_Sebastes-ruberrimus/genetic_data
echo starting bioprj_PRJNA359404_Sebastiscus-marmoratus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA359404_Sebastiscus-marmoratus/genetic_data divdiv_datafiles:bioprj_PRJNA359404_Sebastiscus-marmoratus/genetic_data
echo starting bioprj_PRJNA392526_Sebastiscus-marmoratus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA392526_Sebastiscus-marmoratus/genetic_data divdiv_datafiles:bioprj_PRJNA392526_Sebastiscus-marmoratus/genetic_data
echo starting bioprj_PRJNA319656_Seriola-lalandi-dorsalis
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA319656_Seriola-lalandi-dorsalis/genetic_data divdiv_datafiles:bioprj_PRJNA319656_Seriola-lalandi-dorsalis/genetic_data
echo starting bioprj_PRJNA385011_Siphamia-tubifer
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA385011_Siphamia-tubifer/genetic_data divdiv_datafiles:bioprj_PRJNA385011_Siphamia-tubifer/genetic_data
echo starting bioprj_PRJNA286089_Sphyrna-tiburo
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA286089_Sphyrna-tiburo/genetic_data divdiv_datafiles:bioprj_PRJNA286089_Sphyrna-tiburo/genetic_data
echo starting bioprj_PRJNA448430_Stegastes-beebei
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA448430_Stegastes-beebei/genetic_data divdiv_datafiles:bioprj_PRJNA448430_Stegastes-beebei/genetic_data
echo starting bioprj_PRJNA448430_Stegastes-leucorus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA448430_Stegastes-leucorus/genetic_data divdiv_datafiles:bioprj_PRJNA448430_Stegastes-leucorus/genetic_data
echo starting bioprj_PRJNA361144_Stephanocoenia-intersepta
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA361144_Stephanocoenia-intersepta/genetic_data divdiv_datafiles:bioprj_PRJNA361144_Stephanocoenia-intersepta/genetic_data
echo starting bioprj_PRJNA655996_Strombus-pugilis
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA655996_Strombus-pugilis/genetic_data divdiv_datafiles:bioprj_PRJNA655996_Strombus-pugilis/genetic_data
echo starting bioprj_PRJNA354496_Symphodus-melops
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA354496_Symphodus-melops/genetic_data divdiv_datafiles:bioprj_PRJNA354496_Symphodus-melops/genetic_data
echo starting bioprj_PRJNA361214_Symphodus-tinca
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA361214_Symphodus-tinca/genetic_data divdiv_datafiles:bioprj_PRJNA361214_Symphodus-tinca/genetic_data
echo starting bioprj_PRJNA553831_Systellaspis-debilis
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA553831_Systellaspis-debilis/genetic_data divdiv_datafiles:bioprj_PRJNA553831_Systellaspis-debilis/genetic_data
echo starting bioprj_PRJNA432036_Thunnus-thynnus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA432036_Thunnus-thynnus/genetic_data divdiv_datafiles:bioprj_PRJNA432036_Thunnus-thynnus/genetic_data
echo starting bioprj_PRJNA360511_Trachidermus-fasciatus
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA360511_Trachidermus-fasciatus/genetic_data divdiv_datafiles:bioprj_PRJNA360511_Trachidermus-fasciatus/genetic_data
echo starting bioprj_PRJNA564451_Uria-aalge
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA564451_Uria-aalge/genetic_data divdiv_datafiles:bioprj_PRJNA564451_Uria-aalge/genetic_data
echo starting bioprj_PRJNA564451_Uria-lomvia
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA564451_Uria-lomvia/genetic_data divdiv_datafiles:bioprj_PRJNA564451_Uria-lomvia/genetic_data
echo starting bioprj_PRJNA573759_Vampyroteuthis-infernalis
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA573759_Vampyroteuthis-infernalis/genetic_data divdiv_datafiles:bioprj_PRJNA573759_Vampyroteuthis-infernalis/genetic_data
echo starting bioprj_PRJNA348572_Zalophus-wollebaeki
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA348572_Zalophus-wollebaeki/genetic_data divdiv_datafiles:bioprj_PRJNA348572_Zalophus-wollebaeki/genetic_data
echo starting bioprj_PRJNA449377_Zebrasoma-flavescens
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA449377_Zebrasoma-flavescens/genetic_data divdiv_datafiles:bioprj_PRJNA449377_Zebrasoma-flavescens/genetic_data
echo starting bioprj_PRJNA449377_Zebrasoma-scopas
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJNA449377_Zebrasoma-scopas/genetic_data divdiv_datafiles:bioprj_PRJNA449377_Zebrasoma-scopas/genetic_data
echo starting bioprj_PRJDB7819_Zenarchopterus-dunckeri
rclone copy /mnt/research/Fitz_Lab/bradburd/rht/divdiv_working_popgen/bioprj_PRJDB7819_Zenarchopterus-dunckeri/genetic_data divdiv_datafiles:bioprj_PRJDB7819_Zenarchopterus-dunckeri/genetic_data


