#!/bin/bash

echo starting dataset bioprj_PRJNA371502_Acanthurus-olivaceus
rclone copyto divdiv_datafiles:bioprj_PRJNA553831_Acanthephyra-purpurea/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA553831_Acanthephyra-purpurea.txt
echo starting dataset bioprj_PRJNA473816_Acropora-cervicornis
rclone copyto divdiv_datafiles:bioprj_PRJNA371502_Acanthurus-olivaceus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA371502_Acanthurus-olivaceus.txt
echo starting dataset bioprj_PRJNA593014_Acropora-millepora
rclone copyto divdiv_datafiles:bioprj_PRJNA473816_Acropora-cervicornis/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA473816_Acropora-cervicornis.txt
echo starting dataset bioprj_PRJNA473816_Acropora-palmata
rclone copyto divdiv_datafiles:bioprj_PRJNA593014_Acropora-millepora/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA593014_Acropora-millepora.txt
echo starting dataset bioprj_PRJNA473816_Acropora-prolifera
rclone copyto divdiv_datafiles:bioprj_PRJNA473816_Acropora-palmata/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA473816_Acropora-palmata.txt
echo starting dataset bioprj_PRJNA361144_Agaricia-fragilis
rclone copyto divdiv_datafiles:bioprj_PRJNA473816_Acropora-prolifera/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA473816_Acropora-prolifera.txt
echo starting dataset bioprj_PRJNA385083_Agaricia-undata
rclone copyto divdiv_datafiles:bioprj_PRJNA361144_Agaricia-fragilis/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA361144_Agaricia-fragilis.txt
echo starting dataset bioprj_PRJNA294760_Amphiprion-bicinctus
rclone copyto divdiv_datafiles:bioprj_PRJNA385083_Agaricia-undata/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA385083_Agaricia-undata.txt
echo starting dataset bioprj_PRJNA563695_Amphiprion-clarkii
rclone copyto divdiv_datafiles:bioprj_PRJNA294760_Amphiprion-bicinctus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA294760_Amphiprion-bicinctus.txt
echo starting dataset bioprj_PRJNA295681_Anguilla-anguilla
rclone copyto divdiv_datafiles:bioprj_PRJNA563695_Amphiprion-clarkii/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA563695_Amphiprion-clarkii.txt
echo starting dataset bioprj_PRJNA295681_Anguilla-rostrata
rclone copyto divdiv_datafiles:bioprj_PRJNA295681_Anguilla-anguilla/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA295681_Anguilla-anguilla.txt
echo starting dataset bioprj_PRJNA632874_Anthopleura-elegantissima
rclone copyto divdiv_datafiles:bioprj_PRJNA295681_Anguilla-rostrata/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA295681_Anguilla-rostrata.txt
echo starting dataset bioprj_PRJNA436919_Apostichopus-californicus
rclone copyto divdiv_datafiles:bioprj_PRJNA632874_Anthopleura-elegantissima/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA632874_Anthopleura-elegantissima.txt
echo starting dataset bioprj_PRJNA343012_Aptenodytes-patagonicus
rclone copyto divdiv_datafiles:bioprj_PRJNA436919_Apostichopus-californicus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA436919_Apostichopus-californicus.txt
echo starting dataset bioprj_PRJNA419445_Arctocephalus-forsteri
rclone copyto divdiv_datafiles:bioprj_PRJNA343012_Aptenodytes-patagonicus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA343012_Aptenodytes-patagonicus.txt
echo starting dataset bioprj_PRJNA299372_Aythya-marila
rclone copyto divdiv_datafiles:bioprj_PRJNA419445_Arctocephalus-forsteri/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA419445_Arctocephalus-forsteri.txt
echo starting dataset bioprj_PRJNA542967_Bartholomea-annulata
rclone copyto divdiv_datafiles:bioprj_PRJNA299372_Aythya-marila/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA299372_Aythya-marila.txt
echo starting dataset bioprj_PRJNA595396_Bathygobius-cocosensis
rclone copyto divdiv_datafiles:bioprj_PRJNA542967_Bartholomea-annulata/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA542967_Bartholomea-annulata.txt
echo starting dataset bioprj_PRJNA473646_Bathymodiolus-platifrons
rclone copyto divdiv_datafiles:bioprj_PRJNA595396_Bathygobius-cocosensis/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA595396_Bathygobius-cocosensis.txt
echo starting dataset bioprj_PRJNA646172_Bathyraja-aleutica
rclone copyto divdiv_datafiles:bioprj_PRJNA473646_Bathymodiolus-platifrons/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA473646_Bathymodiolus-platifrons.txt
echo starting dataset bioprj_PRJNA646172_Bathyraja-panthera
rclone copyto divdiv_datafiles:bioprj_PRJNA646172_Bathyraja-aleutica/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA646172_Bathyraja-aleutica.txt
echo starting dataset bioprj_PRJNA646172_Bathyraja-parmifera
rclone copyto divdiv_datafiles:bioprj_PRJNA646172_Bathyraja-panthera/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA646172_Bathyraja-panthera.txt
echo starting dataset bioprj_PRJNA340157_Callinectes-sapidus
rclone copyto divdiv_datafiles:bioprj_PRJNA646172_Bathyraja-parmifera/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA646172_Bathyraja-parmifera.txt
echo starting dataset bioprj_PRJNA559677_Caretta-caretta
rclone copyto divdiv_datafiles:bioprj_PRJNA340157_Callinectes-sapidus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA340157_Callinectes-sapidus.txt
echo starting dataset bioprj_PRJNA286949_Chlorostoma-funebralis
rclone copyto divdiv_datafiles:bioprj_PRJNA559677_Caretta-caretta/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA559677_Caretta-caretta.txt
echo starting dataset bioprj_PRJNA430030_Coryphaenoides-rupestris
rclone copyto divdiv_datafiles:bioprj_PRJNA286949_Chlorostoma-funebralis/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA286949_Chlorostoma-funebralis.txt
echo starting dataset bioprj_PRJNA573759_Cranchia-scabra
rclone copyto divdiv_datafiles:bioprj_PRJNA430030_Coryphaenoides-rupestris/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA430030_Coryphaenoides-rupestris.txt
echo starting dataset bioprj_PRJNA508986_Ctenolabrus-rupestris
rclone copyto divdiv_datafiles:bioprj_PRJNA573759_Cranchia-scabra/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA573759_Cranchia-scabra.txt
echo starting dataset bioprj_PRJNA590458_Dascyllus-trimaculatus
rclone copyto divdiv_datafiles:bioprj_PRJNA508986_Ctenolabrus-rupestris/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA508986_Ctenolabrus-rupestris.txt
echo starting dataset bioprj_PRJNA564823_Delphinapterus-leucas
rclone copyto divdiv_datafiles:bioprj_PRJNA590458_Dascyllus-trimaculatus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA590458_Dascyllus-trimaculatus.txt
echo starting dataset bioprj_PRJNA420851_Ectopleura-larynx
rclone copyto divdiv_datafiles:bioprj_PRJNA564823_Delphinapterus-leucas/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA564823_Delphinapterus-leucas.txt
echo starting dataset bioprj_PRJNA311981_Engraulis-encrasicolus
rclone copyto divdiv_datafiles:bioprj_PRJNA420851_Ectopleura-larynx/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA420851_Ectopleura-larynx.txt
echo starting dataset bioprj_PRJNA523574_Eudyptes-chrysolophus
rclone copyto divdiv_datafiles:bioprj_PRJNA311981_Engraulis-encrasicolus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA311981_Engraulis-encrasicolus.txt
echo starting dataset bioprj_PRJNA576675_Eukrohnia-hamata
rclone copyto divdiv_datafiles:bioprj_PRJNA523574_Eudyptes-chrysolophus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA523574_Eudyptes-chrysolophus.txt
echo starting dataset bioprj_PRJNA394157_Exaiptasia-diaphana
rclone copyto divdiv_datafiles:bioprj_PRJNA576675_Eukrohnia-hamata/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA576675_Eukrohnia-hamata.txt
echo starting dataset bioprj_PRJDB7819_Fibramia-amboinensis
rclone copyto divdiv_datafiles:bioprj_PRJNA394157_Exaiptasia-diaphana/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA394157_Exaiptasia-diaphana.txt
echo starting dataset bioprj_PRJNA629489_Fucus-vesiculosus
rclone copyto divdiv_datafiles:bioprj_PRJDB7819_Fibramia-amboinensis/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJDB7819_Fibramia-amboinensis.txt
echo starting dataset bioprj_PRJNA437462_Fundulus-grandis
rclone copyto divdiv_datafiles:bioprj_PRJNA629489_Fucus-vesiculosus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA629489_Fucus-vesiculosus.txt
echo starting dataset bioprj_PRJNA477712_Fundulus-heteroclitus
rclone copyto divdiv_datafiles:bioprj_PRJNA437462_Fundulus-grandis/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA437462_Fundulus-grandis.txt
echo starting dataset bioprj_PRJNA558810_Gadus-macrocephalus
rclone copyto divdiv_datafiles:bioprj_PRJNA477712_Fundulus-heteroclitus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA477712_Fundulus-heteroclitus.txt
echo starting dataset bioprj_PRJNA528403_Gadus-morhua
rclone copyto divdiv_datafiles:bioprj_PRJNA558810_Gadus-macrocephalus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA558810_Gadus-macrocephalus.txt
echo starting dataset bioprj_PRJNA576132_Galaxea-fascicularis
rclone copyto divdiv_datafiles:bioprj_PRJNA528403_Gadus-morhua/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA528403_Gadus-morhua.txt
echo starting dataset bioprj_PRJNA576132_Galaxea-horrescens
rclone copyto divdiv_datafiles:bioprj_PRJNA576132_Galaxea-fascicularis/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA576132_Galaxea-fascicularis.txt
echo starting dataset bioprj_PRJNA564121_Galaxias-maculatus
rclone copyto divdiv_datafiles:bioprj_PRJNA576132_Galaxea-horrescens/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA576132_Galaxea-horrescens.txt
echo starting dataset bioprj_PRJNA453151_Gasterosteus-aculeatus
rclone copyto divdiv_datafiles:bioprj_PRJNA564121_Galaxias-maculatus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA564121_Galaxias-maculatus.txt
echo starting dataset bioprj_PRJNA448438_Holacanthus-passer
rclone copyto divdiv_datafiles:bioprj_PRJNA453151_Gasterosteus-aculeatus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA453151_Gasterosteus-aculeatus.txt
echo starting dataset bioprj_PRJNA281764_Homarus-americanus
rclone copyto divdiv_datafiles:bioprj_PRJNA448438_Holacanthus-passer/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA448438_Holacanthus-passer.txt
echo starting dataset bioprj_PRJNA551577_Idotea-baltica
rclone copyto divdiv_datafiles:bioprj_PRJNA281764_Homarus-americanus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA281764_Homarus-americanus.txt
echo starting dataset bioprj_PRJNA643849_Isocladus-armatus
rclone copyto divdiv_datafiles:bioprj_PRJNA551577_Idotea-baltica/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA551577_Idotea-baltica.txt
echo starting dataset bioprj_PRJNA553554_Istiblennius-lineatus
rclone copyto divdiv_datafiles:bioprj_PRJNA643849_Isocladus-armatus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA643849_Isocladus-armatus.txt
echo starting dataset bioprj_PRJNA280898_Lagenorhynchus-acutus
rclone copyto divdiv_datafiles:bioprj_PRJNA553554_Istiblennius-lineatus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA553554_Istiblennius-lineatus.txt
echo starting dataset bioprj_PRJNA280898_Lagenorhynchus-albirostris
rclone copyto divdiv_datafiles:bioprj_PRJNA280898_Lagenorhynchus-acutus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA280898_Lagenorhynchus-acutus.txt
echo starting dataset bioprj_PRJNA480409_Laguncularia-racemosa
rclone copyto divdiv_datafiles:bioprj_PRJNA280898_Lagenorhynchus-albirostris/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA280898_Lagenorhynchus-albirostris.txt
echo starting dataset bioprj_PRJNA533707_Larimichthys-polyactis
rclone copyto divdiv_datafiles:bioprj_PRJNA480409_Laguncularia-racemosa/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA480409_Laguncularia-racemosa.txt
echo starting dataset bioprj_PRJNA356786_Lateolabrax-maculatus
rclone copyto divdiv_datafiles:bioprj_PRJNA533707_Larimichthys-polyactis/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA533707_Larimichthys-polyactis.txt
echo starting dataset bioprj_PRJNA521302_Leptopsammia-pruvoti
rclone copyto divdiv_datafiles:bioprj_PRJNA356786_Lateolabrax-maculatus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA356786_Lateolabrax-maculatus.txt
echo starting dataset bioprj_PRJNA329407_Lutjanus-campechanus
rclone copyto divdiv_datafiles:bioprj_PRJNA521302_Leptopsammia-pruvoti/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA521302_Leptopsammia-pruvoti.txt
echo starting dataset bioprj_PRJDB7819_Lutjanus-fulvus
rclone copyto divdiv_datafiles:bioprj_PRJNA329407_Lutjanus-campechanus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA329407_Lutjanus-campechanus.txt
echo starting dataset bioprj_PRJNA631144_Mallotus-villosus
rclone copyto divdiv_datafiles:bioprj_PRJDB7819_Lutjanus-fulvus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJDB7819_Lutjanus-fulvus.txt
echo starting dataset bioprj_PRJNA544861_Montipora-capitata
rclone copyto divdiv_datafiles:bioprj_PRJNA631144_Mallotus-villosus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA631144_Mallotus-villosus.txt
echo starting dataset bioprj_PRJNA564770_Mytilus-galloprovincialis
rclone copyto divdiv_datafiles:bioprj_PRJNA544861_Montipora-capitata/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA544861_Montipora-capitata.txt
echo starting dataset bioprj_PRJNA369717_Nautilus-pompilius
rclone copyto divdiv_datafiles:bioprj_PRJNA564770_Mytilus-galloprovincialis/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA564770_Mytilus-galloprovincialis.txt
echo starting dataset bioprj_PRJNA430897_Nymphon-australe
rclone copyto divdiv_datafiles:bioprj_PRJNA369717_Nautilus-pompilius/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA369717_Nautilus-pompilius.txt
echo starting dataset bioprj_PRJNA343301_Oculina-patagonica
rclone copyto divdiv_datafiles:bioprj_PRJNA430897_Nymphon-australe/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA430897_Nymphon-australe.txt
echo starting dataset bioprj_PRJNA508589_Orbicella-faveolata
rclone copyto divdiv_datafiles:bioprj_PRJNA343301_Oculina-patagonica/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA343301_Oculina-patagonica.txt
echo starting dataset bioprj_PRJNA511386_Ostrea-lurida
rclone copyto divdiv_datafiles:bioprj_PRJNA508589_Orbicella-faveolata/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA508589_Orbicella-faveolata.txt
echo starting dataset bioprj_PRJNA373825_Paracentrotus-lividus
rclone copyto divdiv_datafiles:bioprj_PRJNA511386_Ostrea-lurida/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA511386_Ostrea-lurida.txt
echo starting dataset bioprj_PRJNA640135_Paracirrhites-forsteri
rclone copyto divdiv_datafiles:bioprj_PRJNA373825_Paracentrotus-lividus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA373825_Paracentrotus-lividus.txt
echo starting dataset bioprj_PRJNA477007_Paralichthys-dentatus
rclone copyto divdiv_datafiles:bioprj_PRJNA640135_Paracirrhites-forsteri/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA640135_Paracirrhites-forsteri.txt
echo starting dataset bioprj_PRJNA554161_Penaeus-duorarum
rclone copyto divdiv_datafiles:bioprj_PRJNA477007_Paralichthys-dentatus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA477007_Paralichthys-dentatus.txt
echo starting dataset bioprj_PRJNA450328_Halichoerus-grypus-atlantica
rclone copyto divdiv_datafiles:bioprj_PRJNA554161_Penaeus-duorarum/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA554161_Penaeus-duorarum.txt
echo starting dataset bioprj_PRJNA343959_Phocoena-phocoena
rclone copyto divdiv_datafiles:bioprj_PRJNA450328_Halichoerus-grypus-atlantica/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA450328_Halichoerus-grypus-atlantica.txt
echo starting dataset bioprj_PRJNA659918_Phocoena-sinus
rclone copyto divdiv_datafiles:bioprj_PRJNA343959_Phocoena-phocoena/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA343959_Phocoena-phocoena.txt
echo starting dataset bioprj_PRJNA445895_Pisaster-ochraceus
rclone copyto divdiv_datafiles:bioprj_PRJNA659918_Phocoena-sinus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA659918_Phocoena-sinus.txt
echo starting dataset bioprj_PRJNA471559_Planes-minutus
rclone copyto divdiv_datafiles:bioprj_PRJNA445895_Pisaster-ochraceus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA445895_Pisaster-ochraceus.txt
echo starting dataset bioprj_PRJNA382467_Platichthys-flesus
rclone copyto divdiv_datafiles:bioprj_PRJNA471559_Planes-minutus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA471559_Planes-minutus.txt
echo starting dataset bioprj_PRJNA450871_Pocillopora-damicornis
rclone copyto divdiv_datafiles:bioprj_PRJNA382467_Platichthys-flesus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA382467_Platichthys-flesus.txt
echo starting dataset bioprj_PRJNA280774_Poecilia-latipinna
rclone copyto divdiv_datafiles:bioprj_PRJNA450871_Pocillopora-damicornis/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA450871_Pocillopora-damicornis.txt
echo starting dataset bioprj_PRJNA559876_Pomacanthus-maculosus
rclone copyto divdiv_datafiles:bioprj_PRJNA280774_Poecilia-latipinna/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA280774_Poecilia-latipinna.txt
echo starting dataset bioprj_PRJNA379028_Porites-astreoides
rclone copyto divdiv_datafiles:bioprj_PRJNA559876_Pomacanthus-maculosus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA559876_Pomacanthus-maculosus.txt
echo starting dataset bioprj_PRJNA544861_Porites-compressa
rclone copyto divdiv_datafiles:bioprj_PRJNA379028_Porites-astreoides/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA379028_Porites-astreoides.txt
echo starting dataset bioprj_PRJNA493660_Pygoscelis-adeliae
rclone copyto divdiv_datafiles:bioprj_PRJNA544861_Porites-compressa/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA544861_Porites-compressa.txt
echo starting dataset bioprj_PRJNA493660_Pygoscelis-antarcticus
rclone copyto divdiv_datafiles:bioprj_PRJNA493660_Pygoscelis-adeliae/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA493660_Pygoscelis-adeliae.txt
echo starting dataset bioprj_PRJNA493660_Pygoscelis-papua
rclone copyto divdiv_datafiles:bioprj_PRJNA493660_Pygoscelis-antarcticus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA493660_Pygoscelis-antarcticus.txt
echo starting dataset bioprj_PRJNA573759_Pyroteuthis-margaritifera
rclone copyto divdiv_datafiles:bioprj_PRJNA493660_Pygoscelis-papua/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA493660_Pygoscelis-papua.txt
echo starting dataset bioprj_PRJNA480308_Rhizophora-mangle
rclone copyto divdiv_datafiles:bioprj_PRJNA573759_Pyroteuthis-margaritifera/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA573759_Pyroteuthis-margaritifera.txt
echo starting dataset bioprj_PRJNA553831_Robustosergia-robusta
rclone copyto divdiv_datafiles:bioprj_PRJNA480308_Rhizophora-mangle/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA480308_Rhizophora-mangle.txt
echo starting dataset bioprj_PRJNA549138_Sargassum-muticum
rclone copyto divdiv_datafiles:bioprj_PRJNA553831_Robustosergia-robusta/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA553831_Robustosergia-robusta.txt
echo starting dataset bioprj_PRJNA253681_Scomber-scombrus
rclone copyto divdiv_datafiles:bioprj_PRJNA549138_Sargassum-muticum/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA549138_Sargassum-muticum.txt
echo starting dataset bioprj_PRJNA560239_Sebastes-diaconus
rclone copyto divdiv_datafiles:bioprj_PRJNA253681_Scomber-scombrus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA253681_Scomber-scombrus.txt
echo starting dataset bioprj_PRJNA451040_Sebastes-paucispinis
rclone copyto divdiv_datafiles:bioprj_PRJNA560239_Sebastes-diaconus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA560239_Sebastes-diaconus.txt
echo starting dataset bioprj_PRJNA451040_Sebastes-pinniger
rclone copyto divdiv_datafiles:bioprj_PRJNA451040_Sebastes-paucispinis/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA451040_Sebastes-paucispinis.txt
echo starting dataset bioprj_PRJNA316872_Sebastes-rastrelliger
rclone copyto divdiv_datafiles:bioprj_PRJNA451040_Sebastes-pinniger/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA451040_Sebastes-pinniger.txt
echo starting dataset bioprj_PRJNA451040_Sebastes-ruberrimus
rclone copyto divdiv_datafiles:bioprj_PRJNA316872_Sebastes-rastrelliger/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA316872_Sebastes-rastrelliger.txt
echo starting dataset bioprj_PRJNA359404_Sebastiscus-marmoratus
rclone copyto divdiv_datafiles:bioprj_PRJNA451040_Sebastes-ruberrimus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA451040_Sebastes-ruberrimus.txt
echo starting dataset bioprj_PRJNA319656_Seriola-lalandi-dorsalis
rclone copyto divdiv_datafiles:bioprj_PRJNA359404_Sebastiscus-marmoratus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA359404_Sebastiscus-marmoratus.txt
echo starting dataset bioprj_PRJNA385011_Siphamia-tubifer
rclone copyto divdiv_datafiles:bioprj_PRJNA319656_Seriola-lalandi-dorsalis/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA319656_Seriola-lalandi-dorsalis.txt
echo starting dataset bioprj_PRJNA286089_Sphyrna-tiburo
rclone copyto divdiv_datafiles:bioprj_PRJNA385011_Siphamia-tubifer/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA385011_Siphamia-tubifer.txt
echo starting dataset bioprj_PRJNA448430_Stegastes-beebei
rclone copyto divdiv_datafiles:bioprj_PRJNA286089_Sphyrna-tiburo/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA286089_Sphyrna-tiburo.txt
echo starting dataset bioprj_PRJNA448430_Stegastes-leucorus
rclone copyto divdiv_datafiles:bioprj_PRJNA448430_Stegastes-beebei/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA448430_Stegastes-beebei.txt
echo starting dataset bioprj_PRJNA361144_Stephanocoenia-intersepta
rclone copyto divdiv_datafiles:bioprj_PRJNA448430_Stegastes-leucorus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA448430_Stegastes-leucorus.txt
echo starting dataset bioprj_PRJNA655996_Strombus-pugilis
rclone copyto divdiv_datafiles:bioprj_PRJNA361144_Stephanocoenia-intersepta/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA361144_Stephanocoenia-intersepta.txt
echo starting dataset bioprj_PRJNA354496_Symphodus-melops
rclone copyto divdiv_datafiles:bioprj_PRJNA655996_Strombus-pugilis/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA655996_Strombus-pugilis.txt
echo starting dataset bioprj_PRJNA361214_Symphodus-tinca
rclone copyto divdiv_datafiles:bioprj_PRJNA354496_Symphodus-melops/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA354496_Symphodus-melops.txt
echo starting dataset bioprj_PRJNA553831_Systellaspis-debilis
rclone copyto divdiv_datafiles:bioprj_PRJNA361214_Symphodus-tinca/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA361214_Symphodus-tinca.txt
echo starting dataset bioprj_PRJNA432036_Thunnus-thynnus
rclone copyto divdiv_datafiles:bioprj_PRJNA553831_Systellaspis-debilis/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA553831_Systellaspis-debilis.txt
echo starting dataset bioprj_PRJNA360511_Trachidermus-fasciatus
rclone copyto divdiv_datafiles:bioprj_PRJNA432036_Thunnus-thynnus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA432036_Thunnus-thynnus.txt
echo starting dataset bioprj_PRJNA564451_Uria-aalge
rclone copyto divdiv_datafiles:bioprj_PRJNA360511_Trachidermus-fasciatus/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA360511_Trachidermus-fasciatus.txt
echo starting dataset bioprj_PRJNA564451_Uria-lomvia
rclone copyto divdiv_datafiles:bioprj_PRJNA564451_Uria-aalge/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA564451_Uria-aalge.txt
echo starting dataset bioprj_PRJNA573759_Vampyroteuthis-infernalis
rclone copyto divdiv_datafiles:bioprj_PRJNA564451_Uria-lomvia/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA564451_Uria-lomvia.txt
echo starting dataset bioprj_PRJNA348572_Zalophus-wollebaeki
rclone copyto divdiv_datafiles:bioprj_PRJNA573759_Vampyroteuthis-infernalis/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA573759_Vampyroteuthis-infernalis.txt
echo starting dataset bioprj_PRJNA449377_Zebrasoma-flavescens
rclone copyto divdiv_datafiles:bioprj_PRJNA348572_Zalophus-wollebaeki/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA348572_Zalophus-wollebaeki.txt
echo starting dataset bioprj_PRJNA449377_Zebrasoma-scopas
rclone copyto divdiv_datafiles:bioprj_PRJNA449377_Zebrasoma-flavescens/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA449377_Zebrasoma-flavescens.txt
echo starting dataset bioprj_PRJDB7819_Zenarchopterus-dunckeri
rclone copyto divdiv_datafiles:bioprj_PRJNA449377_Zebrasoma-scopas/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJNA449377_Zebrasoma-scopas.txt
rclone copyto divdiv_datafiles:bioprj_PRJDB7819_Zenarchopterus-dunckeri/samplenamekey.txt 
/Users/rachel/divdiv/data/all_samplenamekeys/samplenamekey-bioprj_PRJDB7819_Zenarchopterus-dunckeri.txt

